apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2022-04-11T06:20:47Z","labels":{"app.kubernetes.io/instance":"ks-versions"},"name":"devops-agent-v3.2.1-rc.3","namespace":"ks-version"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/kubesphere-sigs/ks-versions","branch":"master","name":"ks-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"auto","address":"https://github.com/kubesphere/devops-agent","branch":"master","name":"devops-agent","provider":"github","version":"v3.2.1-rc.3"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v3.2.1-rc.3"},"status":{}}
    releaser.devops.kubesphere.io/hash: 7fc84dd5c6
  creationTimestamp: "2022-04-11T07:07:43Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: ks-versions
  name: devops-agent-v3.2.1-rc.3
  namespace: ks-version
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/ks-version/releasers/devops-agent-v3.2.1-rc.3
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: auto
    address: https://github.com/kubesphere/devops-agent
    branch: master
    name: devops-agent
    provider: github
    version: v3.2.1-rc.3
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v3.2.1-rc.3
status:
  conditions:
  - conditionType: release
    message: https://github.com/kubesphere/devops-agent was released
    status: success
