apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  name: ks-releaser-v0.0.9
  namespace: ks-version
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/kubesphere-sigs/ks-releaser
    branch: master
    name: ks-releaser
    provider: github
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.9
