apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2021-11-06T15:52:30Z","labels":{"app.kubernetes.io/instance":"ks-version"},"name":"ks-releaser-v0.0.13","namespace":"ks-version"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/kubesphere-sigs/ks-versions","branch":"master","name":"ks-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/kubesphere-sigs/ks-releaser","branch":"master","name":"ks-releaser","provider":"github","version":"v0.0.13"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.13"},"status":{}}
    releaser.devops.kubesphere.io/hash: 795d6555c7
  creationTimestamp: "2021-11-08T06:55:32Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: ks-version
  name: ks-releaser-v0.0.13
  namespace: ks-version
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/ks-version/releasers/ks-releaser-v0.0.13
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/kubesphere-sigs/ks-releaser
    branch: master
    name: ks-releaser
    provider: github
    version: v0.0.13
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.13
status:
  conditions:
  - conditionType: release
    message: https://github.com/kubesphere-sigs/ks-releaser was released
    status: success
