apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2022-03-07T06:32:54Z","labels":{"app.kubernetes.io/instance":"ks-versions"},"name":"ks-v0.0.64","namespace":"ks-version"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/kubesphere-sigs/ks-versions","branch":"master","name":"ks-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/kubesphere-sigs/ks","branch":"master","name":"ks","provider":"github","version":"v0.0.64"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.64"},"status":{}}
    releaser.devops.kubesphere.io/hash: 648ffcff49
  creationTimestamp: "2022-04-01T07:55:16Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: ks-versions
  name: ks-v0.0.64
  namespace: ks-version
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/ks-version/releasers/ks-v0.0.64
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/kubesphere-sigs/ks
    branch: master
    name: ks
    provider: github
    version: v0.0.64
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.64
status:
  conditions:
  - conditionType: release
    message: https://github.com/kubesphere-sigs/ks was released
    status: success
