apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-11-24T10:57:14Z"
  labels:
    app.kubernetes.io/instance: ks-version
  name: ks-devops-v3.2.1-rc.2
  namespace: ks-version
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: draft
  repositories:
  - action: pre-release
    address: https://github.com/kubesphere/ks-devops
    branch: release-3.2
    name: ks-devops
    provider: github
    version: v3.2.1-rc.2
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v3.2.1-rc.2
status: {}
