apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ks-version"},"name":"ks-v0.0.57","namespace":"ks-version"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/kubesphere-sigs/ks-versions","branch":"master","name":"ks-versions"}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/kubesphere-sigs/ks","branch":"master","name":"ks"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.57"},"status":{}}
    releaser.devops.kubesphere.io/hash: 79568b78b4
  creationTimestamp: "2021-11-04T06:36:50Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: ks-version
  name: ks-v0.0.57
  namespace: ks-version
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/ks-version/releasers/ks-v0.0.57
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/kubesphere-sigs/ks
    branch: master
    name: ks
    provider: github
    version: v0.0.57
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.57
status:
  conditions:
  - conditionType: release
    message: https://github.com/kubesphere-sigs/ks was released
    status: success
