apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-12-25T08:08:40Z"
  labels:
    app.kubernetes.io/instance: ks-versions
  name: kubekey-v2.0.0-rc.1
  namespace: ks-version
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret:
      name: linuxsuren-bot
      namespace: ks-releaser-system
  phase: ready
  repositories:
  - action: pre-release
    address: https://github.com/kubesphere/kubekey
    branch: release-2.0
    name: kubekey
    provider: github
    version: v2.0.0-rc.1
  secret:
    name: release-bot
    namespace: release
  version: v2.0.0-rc.1
status: {}
