apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2022-02-18T09:41:37Z","labels":{"app.kubernetes.io/instance":"ks-versions"},"name":"kubekey-v2.0.0","namespace":"ks-version"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/kubesphere-sigs/ks-versions","branch":"master","name":"ks-versions","provider":"github"},"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"}},"phase":"ready","repositories":[{"action":"pre-release","address":"https://github.com/kubesphere/kubekey","branch":"release-2.0","name":"kubekey","provider":"github","version":"v2.0.0"}],"secret":{"name":"release-bot","namespace":"release"},"version":"v2.0.0"},"status":{}}
    releaser.devops.kubesphere.io/hash: 9f4689956
  creationTimestamp: "2022-04-08T02:48:09Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: ks-versions
  name: kubekey-v2.0.0
  namespace: ks-version
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/ks-version/releasers/kubekey-v2.0.0
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/kubesphere-sigs/ks-versions
      branch: master
      name: ks-versions
      provider: github
    secret:
      name: linuxsuren-bot
      namespace: ks-releaser-system
  phase: done
  repositories:
  - action: pre-release
    address: https://github.com/kubesphere/kubekey
    branch: release-2.0
    name: kubekey
    provider: github
    version: v2.0.0
  secret:
    name: release-bot
    namespace: release
  version: v2.0.0
status:
  conditions:
  - conditionType: release
    message: https://github.com/kubesphere/kubekey was released
    status: success
